### ISSUE TITLE
First kitten doesn't appear until 200 words

### ISSUE THREAD

**Issue by Skud** [joshuawalcher/writtenkitten-original#4]
A report from a user, by email:

> Hi! I really like "Written Kitten"! But it's hasn't been working for me for the last week or two; I haven't been seeing new kittens after writing 100 words, smile. If you could help, that would be great!

My followup:

> Thanks, I'll look into it.  I haven't had any other reports but will try to replicate it.
> 
> Can you tell me if it happens when you reload the page completely fresh in your browser, with shift-reload?

Their response:

> Hi! Just wanted to let you know that I'm still not receiving kittens after 100 words--although I do after 200 words. I've tried shift-reloading, but that doesn't help, and I tried it in Internet Explorer and Google Chrome on two different computers, and my son tried it on his laptop, too. (As you can tell, I like Written Kitten  :)

I have replicated the bug, so it is actually a thing.

**Comment by qualiyah** [comment]
I also have this problem, it appears. I actually thought I just wasn't getting any kittens at *all*, and was super sad. I did try reloading the page and the problem is consistent.

Thank you for your otherwise awesome program!

**Comment by joshuawalcher** [comment]
It's because the first kitten hasn't been fetched on page load. I will add a pull request with the fix.
