### ISSUE TITLE
Anyone want to take over WK?

### ISSUE THREAD

**Issue by Skud** [joshuawalcher/writtenkitten-original#9]
Sadly, I no longer have the motivation to maintain Written? Kitten!, so I’m looking for someone to take it over.

This would involve:
- I transfer the domain to you, and you continue to keep it up and running or at least smoothly transition to something else (eg. with a redirect for a year or two)
- Web-hosting wise, you simply need to host a single static HTML file; it gets about 25k-50k hits a month, sometimes spiking in November during NaNoWriMo (the most was its first NaNo, at 235k visits in Nov 2011.)
- You take over ownership of this github repo and deal with very occasional bugfixes, improvements, etc. 

I’d ask that you continue to attribute me and Emily as the creators, and to make it available under the BSD license it currently has.

Anyone want it?

**Comment by rahaeli** [comment]
I would probably likely be an equally laissez-faire maintainer, so should not be a first choice, but if nobody steps up I'd take it!

**Comment by etfb** [comment]
I'm technically competent to do this, and I have no problem with the time/effort commitment if it's within 500% of what you say.  That said, I have my own web hosting with a bog-standard $20-a-month Australian company (with, it must be said, excellent service and a lot of leeway to mess around with my system, so I can't complain) and it may well be that 50khits a month would be too much for it, in which case I would have to drop it like a hot potato.  **I just don't know.**

But: **if** you are still looking for someone in a couple of weeks and have had no takers, you know where to find me.  If you want me to prove my skillz (or, possibly, demonstrate how totally Dunning Kruger I am and tell me I'm an idiot) I'm open to that too.  Just no trial by combat; I have a bodgy elbow so I can't manage a sword.

: Bat :

**Comment by Skud** [comment]
@etfb If you want to prove your skilz (for your own satisfaction and 
comfort, not mine) feel free to take a look at the pull requests that 
are currently here and code review them.  If they make sense to you and 
you'd feel confident applying them, then you'd do fine :)

On 3/04/2015 9:23 pm, etfb wrote:
>
> I'm technically competent to do this, and I have no problem with the 
> time/effort commitment if it's within 500% of what you say. That said, 
> I have my own web hosting with a bog-standard $20-a-month Australian 
> company (with, it must be said, excellent service and a lot of leeway 
> to mess around with my system, so I can't complain) and it may well be 
> that 50khits a month would be too much for it, in which case I would 
> have to drop it like a hot potato. *I just don't know.*
>
> But: *if* you are still looking for someone in a couple of weeks and 
> have had no takers, you know where to find me. If you want me to prove 
> my skillz (or, possibly, demonstrate how totally Dunning Kruger I am 
> and tell me I'm an idiot) I'm open to that too. Just no trial by 
> combat; I have a bodgy elbow so I can't manage a sword.
>
> : Bat :
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Skud/writtenkitten/issues/9#issuecomment-89248773>.
>

-- 
Alex "Skud" Bayley
skud@infotrope.net
http://infotrope.net

**Comment by Fil** [comment]
I can offer help & hosting as well — I can second @raheli & @etfb

**Comment by TechieFlowerChild** [comment]
This is just the sort of thing I am looking for! I have tons of questions...no issue with committment...just want to make sure I am the right person and not getting in over my head.

**Comment by joshuawalcher** [comment]
Hey Skud, I'd like to take it over. I run a small web hosting company and have lots of bandwidth available. I'm also a PHP/JavaScript programmer as my every day job, so any bug reports or feature requests will be easy for me to handle

 I've already put up two mirrors of the site since the writtenkitten.net hosting account seems to have shut down.

My github name is also my Gmail. Please contact me and I will get the main site back up ASAP on my server farm.

**Comment by Mmelizal** [comment]
Is there any reason that WK is down right now? I had work saved and can't get the page to come up. Help! My email is mmelizalde@ucdavis.edu

**Comment by joshuawalcher** [comment]
I haven't seen writtenkitten.net online for two weeks now, @Mmelizal. You can use the mirror I am hosting until Skud replies at:
http://www.bigboardroom.com/writtenkitten/

**Comment by Mmelizal** [comment]
Thank you @joshuawalcher!

**Comment by NicolasSalomon** [comment]
I'd be willing to take hosting and the eventual bug fixing over!

**Comment by SeanKilleen** [comment]
@Skud I think I'd be willing to take this over if you want. It's a great idea/app and I've recommended it to people a bunch. Happy to keep the license / credit / OSS nature of the app. 

Changes I'd probably make (eventually):

* **Move to hosting via GitHub pages**: It's free, and it's backed by GitHub's infrastructure. The site is already coded in such a way that this would be an easy transition. I'd do this early on as part of the transfer. 
* **Move toward MVVM**: I'd probably update the site from jQuery to a Knockout viewmodel.
* **Put some tests around it**: Mostly as an exercise. I'm trying to get myself more familiar with Jasmine, etc. and this seems like a nice-size use case.

**Comment by joshuawalcher** [comment]
Sean, I took it over a couple of months ago and the code and fixes now reside at writtenkitten.co. Skud didn't reply to my messages here or on Twitter, so the domain has lapsed to someone (or more likely, somebot) else at this point.
